# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5f4e482b75a39ffe1a05d78faf6fa8e7d0fb5b41b688b6f8be204d1374afb842879732f0b6b2c5d959336179fbf04aa2655b3f69453fa5cf3318fa8ebdc854cc

test:
  secret_key_base: 6d685fa2dfbbaa7a84cd8769f64fe0d8aaf823c3e98193a747dc753737b1bc08716be16fd7817810c3bbac006ff6f79e6ec530f1dbf4a856153a79d7b56b0f72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
